name: Build

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - ./*.py
      - uv.lock
      - pyproject.toml

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows]
    name: "Build: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python install 3.12
          uv sync --python 3.12

      - name: Configure venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Build binary
        run: |
          uv run pyinstaller -Fw -i assets/images/icon.png --name Pac-man main.py
          mv assets/ dist/

      - uses: actions/upload-artifact@v4
        with:
          name: Pac-man_${{ matrix.os }}
          path: dist/
